name: Build and Train

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: mlops-cluster
  ECR_REPO: mlops

jobs:
  build-train:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- AWS LOGIN (OIDC) ----
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Docker Buildx
        run: |
          docker buildx create --use --name builder
          docker buildx inspect --bootstrap

      # ---- ECR LOGIN ----
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # ---- BUILD & PUSH ----
      - name: Build and Push image (with registry cache)
        run: |
          cd train && docker buildx build \
            --platform linux/amd64 \
            --tag 021518179741.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG \
            --tag 021518179741.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest \
            --cache-from=type=registry,ref=021518179741.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:buildcache \
            --cache-to=type=registry,ref=021518179741.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:buildcache,mode=max \
            --push \
            .

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.0'

      # ---- CONNECT TO EKS ----
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      # ---- START TRAINING ----
      - name: Submit training job
        run: |
          sed "s|IMAGE_TAG|$IMAGE_TAG|g" k8s/train-job.yaml | kubectl apply -f -
